### ISSUE TITLE
New riddles

### ISSUE THREAD

**Issue by av** [cpldcpu/MisguidedAttention#4]
Here're some new simple misguided riddles

**I'm tall when I'm young, and I'm taller when I'm old. What am I?**
Definitely not a candle

**I'm tall when I'm young, and I'm taller when I'm old. What am I?**
Definitely not a promise

**What goes up but never comes up again?**
Definitely not your age

**I never shave, but my beard stays the same. What am I?**
Definitely not a barber

**Comment by cpldcpu** [comment]
Wow, thanks, those are great. It's a fully new angle to this phenomenon - riddles instead of logic problems.

The second one seems to be a copy of the first one. Is that intentional?

The LLMs try pretty hard to shoehorn "candle" into the solution of the first one.
![grafik](https://github.com/user-attachments/assets/7d5522a8-26c2-4220-a295-d8e14746c9fa)

![grafik](https://github.com/user-attachments/assets/999ff933-85f8-4f26-9567-62639d515a1b)

![grafik](https://github.com/user-attachments/assets/9ffa23d6-1b6a-48bb-b716-488d5641ee0e)

**Comment by av** [comment]
> The second one seems to be a copy of the first one. Is that intentional?

You're not misguided as easily, the second one should be this:
**What can't you break, even if you never pick it up or touch it?**

**Comment by av** [comment]
Another one, found on ChatGPT Reddit:

**The surgeon, who is the boy's father says, "I can't operate on this boy, he's my son!" Who is the surgeon to the boy?**
-

[Source](https://www.reddit.com/r/ChatGPT/comments/1ff9w7y/new_o1_still_fails_miserably_at_trivial_questions/)

**Comment by cpldcpu** [comment]
I am currently setting up evals on the dataset. Had to laugh about this:

![grafik](https://github.com/user-attachments/assets/1c77be88-a97f-4116-87e6-c330f362119b)

**Comment by av** [comment]
Yes, I observed this as well! 

I consider this a pass from the misguided attention point of view, but a fail from the bias point of view :)

I recently built a LLM-as-a-judge bench that is centered around the custom tasks, was using misguided tasks as a baseline. Looks like this:

```yaml
- tags: [attention]
  question: Which is heavier, 1 kilogram of feathers or 1 pound of steel?
  criteria:
    correctness: 1 kilogram of feathers is mentioned as being heavier
    reasoning: It is mentioned that 1 kilogram is heavier than 1 pound

- tags: [attention]
  question: If you have a 5-gallon jug and a 3-gallon jug, how can you measure exactly 8 gallons of water?
  criteria:
    correctness: Answer mentions that both jugs need to be filled only once which will add up to 8 gallons
    reasoning: Answer doesn't suggest emptying and filling the jugs multiple times
```

I  can finish the dataset and share the instruction on running the eval if you're interested
